import 'package:intl/intl.dart';
import 'package:foodsnap/models/diary.dart';

final List<Diary> dummyDiaries = [
  Diary(
    title: 'Chicken rice',
    comment: 'This chicken rice is delicious!',
    calorie: 600,
    imagePath: 'assets/images/diary_dummydata/chickenrice.jpg',
    createdTime: DateTime(2023, 7, 13),
    editedTime: DateTime(2023, 7, 13),
    user: 'Benny',
  ),
  Diary(
    title: 'Lobster roll',
    comment: 'Food is bussin and scrumptuous',
    calorie: 433,
    imagePath: 'assets/images/diary_dummydata/lobsterroll.jpg',
    createdTime: DateTime(2023, 8, 11),
    editedTime: DateTime(2023, 8, 11),
    user: 'Benny',
  ),
  Diary(
    title: 'Cheese Pizza',
    comment: 'Cheesy goodness!',
    calorie: 1102,
    imagePath: 'assets/images/diary_dummydata/cheesepizza.jpg',
    createdTime: DateTime(2023, 9, 1),
    editedTime: DateTime(2023, 9, 3),
    user: 'Benny',
  ),
  Diary(
    title: 'Chicken parmesan',
    comment: 'I bought this meal at shake shack. I did not know shake shack had a secret menu! Very tasty!',
    calorie: 402,
    imagePath: 'assets/images/diary_dummydata/chickenparm.jpg',
    createdTime: DateTime(2023, 9, 2),
    editedTime: DateTime(2023, 9, 3),
    user: 'Benny',
  ),
  Diary(
    title: 'Chicken Katsu',
    comment: 'Bought this at Japan. Very crunchy.',
    calorie: 355,
    imagePath: 'assets/images/diary_dummydata/chickenkatsu.jpeg',
    createdTime: DateTime(2023, 8, 29),
    editedTime: DateTime(2023, 9, 3),
    user: 'Benny',
  ),
  Diary(
    title: 'Mac n cheese',
    comment: 'Super cheesy. It was so slimy!',
    calorie: 1203,
    imagePath: 'assets/images/diary_dummydata/macncheese.jpg',
    createdTime: DateTime(2023, 9, 2),
    editedTime: DateTime(2023, 9, 3),
    user: 'Benny',
  ),
  Diary(
    title: 'Ramen',
    comment: 'This ramen hit me in the spot! It was amazing',
    calorie: 645,
    imagePath: 'assets/images/diary_dummydata/ramen.jpg',
    createdTime: DateTime(2023, 9, 3),
    editedTime: DateTime(2023, 9, 3),
    user: 'Benny',
  ),
  Diary(
    title: 'Mushroom swiss burger',
    comment: 'Trying to eat a burger other than just plain meat and cheese. Mushrooms are love.',
    calorie: 890,
    imagePath: 'assets/images/diary_dummydata/swissburger.jpeg',
    createdTime: DateTime(2023, 9, 1),
    editedTime: DateTime(2023, 9, 3),
    user: 'Benny',
  ),
  Diary(
    title: 'Chocolate cake',
    comment: 'Super sweet. Probably should not have ate this.',
    calorie: 677,
    imagePath: 'assets/images/diary_dummydata/chocolatecake.jpg',
    createdTime: DateTime(2023, 8, 5),
    editedTime: DateTime(2023, 8, 7),
    user: 'Benny',
  ),
  Diary(
    title: 'Butter chicken',
    comment: 'Love the sweet and tangy sauce to it!',
    calorie: 876,
    imagePath: 'assets/images/diary_dummydata/butterchicken.jpeg',
    createdTime: DateTime(2023, 9, 1),
    editedTime: DateTime(2023, 9, 3),
    user: 'Benny',
  ),
];
